### ISSUE TITLE
[Bug] 使用hyoeros双开功能，模块失效

### ISSUE THREAD

**Issue by xueshiji** [xihan123/QDReadHook#258]
### 复现步骤

1. 使用hyperos双开功能，双开起点app和模块app
2. 授予两个特殊权限
3. 模块失效

### 预期行为

模块正常注入

### 实际行为

注入失败

### LSPosed 版本

7058

### Android 版本

14

### 模块 版本

528

### 起点 版本

1316

### Logs/日志

[ 2024-07-04T17:45:48.588 99910474: 19603: 19603 E/LSPosed-Bridge  ]     Failed to load class cn.xihan.qdds.hook.HookEntry_YukiHookXposedInit
java.lang.ExceptionInInitializerError
	at LPT3.default.<init>(希涵:4)
	at LPT3.finally.<clinit>(希涵:3)
	at cn.xihan.qdds.hook.HookEntry_YukiHookXposedInit.initZygote(希涵:1)
	at de.robv.android.xposed.XposedInit.initModule(Unknown Source:82)
	at de.robv.android.xposed.XposedInit.loadModule(Unknown Source:144)
	at de.robv.android.xposed.XposedInit.lambda$loadLegacyModules$0(Unknown Source:15)
	at de.robv.android.xposed.XposedInit.b(Unknown Source:0)
	at O0.accept(Unknown Source:13)
	at java.util.ArrayList.forEach(ArrayList.java:1528)
	at de.robv.android.xposed.XposedInit.loadLegacyModules(Unknown Source:12)
	at org.lsposed.lspd.core.Main.forkCommon(Unknown Source:238)
	at com.android.internal.os.Zygote.nativeForkAndSpecialize(Native Method)
	at com.android.internal.os.Zygote.forkAndSpecialize(Zygote.java:365)
	at com.android.internal.os.ZygoteConnection.processCommand(ZygoteConnection.java:257)
	at com.android.internal.os.ZygoteServer.runSelectLoop(ZygoteServer.java:521)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1000)
Caused by: java.lang.SecurityException: Need INTERACT_ACROSS_USERS to get volumes for another user: Neither user 99910474 nor current process has android.permission.INTERACT_ACROSS_USERS.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.os.storage.IStorageManager$Stub$Proxy.getVolumeList(IStorageManager.java:1521)
	at android.os.storage.StorageManager.getVolumeList(StorageManager.java:1438)
	at android.os.Environment$UserEnvironment.getExternalDirs(Environment.java:184)
	at android.os.Environment$UserEnvironment.buildExternalStoragePublicDirs(Environment.java:204)
	at android.os.Environment.getExternalStoragePublicDirectory(Environment.java:1091)
	at cn.xihan.qdds.util.assert.<clinit>(希涵:42)
	... 16 more

**Comment by xihan123** [comment]
你试试这个版本修复没
[QDReadHook-v3.1.9-536-universal.zip](https://github.com/user-attachments/files/16105295/QDReadHook-v3.1.9-536-universal.zip)

**Comment by xueshiji** [comment]
可以了，大佬牛逼

> 你试试这个版本修复没 [QDReadHook-v3.1.9-536-universal.zip](https://github.com/user-attachments/files/16105295/QDReadHook-v3.1.9-536-universal.zip)
